import { computed } from 'vue'

export const createSidebarBindings = (ctx) => computed(() => ({
  showBusinessSidebar: ctx.showBusinessSidebar.value,
  pwdLogo: ctx.pwdLogo,
  businessName: ctx.businessSidebarBrandName.value,
  businessBrandSubtitle: ctx.businessSidebarBrandSubtitle.value,
  profileName: ctx.loggedInBusinessUserName.value,
  profileAvatar: ctx.loggedInBusinessUserAvatar.value,
  profileInitials: ctx.loggedInBusinessUserInitials.value,
  profileEmail: ctx.loggedInBusinessUserEmail.value,
  profileRoleLabel: ctx.loggedInBusinessUserRoleLabel.value,
  secondarySectionLabel: ctx.businessSidebarSecondarySectionLabel.value,
  showBusinessSubscriptionShortcut: ctx.canAccessOwnerWorkspaceControls.value,
  showBusinessProfileShortcut: ctx.canAccessOwnerWorkspaceControls.value,
  sidebarGroups: ctx.sidebarGroups.value,
  activeSection: ctx.activeSection.value,
  activeSidebarGroup: ctx.activeSidebarGroup.value,
  expandedSidebarGroups: ctx.expandedSidebarGroups.value,
  openSidebarGroup: ctx.openSidebarGroup,
  handleSidebarSectionClick: ctx.handleSidebarSectionClick,
  setSidebarLinkRef: ctx.setSidebarLinkRef,
  getSidebarItemIcon: ctx.getSidebarItemIcon,
  isPremiumGuideTarget: ctx.isPremiumGuideTarget,
  isLogoutSubmitting: ctx.isLogoutSubmitting.value,
  openLogoutConfirm: ctx.openLogoutConfirm,
  openBusinessSubscriptionSection: ctx.openBusinessSubscriptionSection,
  openBusinessProfileSection: ctx.openBusinessProfileSection,
}))

export const createNavbarBindings = (ctx) => computed(() => ({
  currentSection: ctx.currentSection.value,
  breadcrumbParent: ctx.businessNavbarBreadcrumbParent.value,
  businessName: ctx.loggedInBusinessUserName.value,
  businessEmail: ctx.loggedInBusinessUserEmail.value,
  businessInitials: ctx.loggedInBusinessUserInitials.value,
  profileAvatar: ctx.loggedInBusinessUserAvatar.value,
  profileRoleLabel: ctx.loggedInBusinessUserRoleLabel.value,
  workspaceOwnerName: ctx.businessWorkspaceOwnerName.value,
  isProfileMenuOpen: ctx.isProfileMenuOpen.value,
  businessNavbarSettingsItems: ctx.businessNavbarSettingsItems.value,
  businessNavbarNotifications: ctx.businessNavbarNotifications.value,
  unreadBusinessNotificationCount: ctx.unreadBusinessNotificationCount.value,
  isNotificationMenuOpen: ctx.isNotificationMenuOpen.value,
  toggleBusinessProfileMenu: ctx.toggleBusinessProfileMenu,
  toggleNotificationMenu: ctx.toggleNotificationMenu,
  openBusinessNotification: ctx.openBusinessNotification,
  handleBusinessNavbarSetting: ctx.handleBusinessNavbarSetting,
  openLogoutConfirm: ctx.openLogoutConfirm,
}))

export const createModalBindings = (ctx) => computed(() => ({
  isApplicantManagementModalOpen: ctx.isApplicantManagementModalOpen.value,
  closeApplicantManagementModal: ctx.closeApplicantManagementModal,
  applicantManagementModalState: ctx.applicantManagementModalState,
  selectedApplicantManagementDetails: ctx.selectedApplicantManagementDetails.value,
  buildUserOverviewInitials: ctx.buildUserOverviewInitials,
  normalizeUserOverviewValue: ctx.normalizeUserOverviewValue,
  isApplicantManagementDecisionSubmitting: ctx.isApplicantManagementDecisionSubmitting.value,
  canUpdateSelectedApplicantManagementStatus: ctx.canUpdateSelectedApplicantManagementStatus.value,
  approveApplicantManagementApplication: ctx.approveApplicantManagementApplication,
  rejectApplicantManagementApplication: ctx.rejectApplicantManagementApplication,
  isBusinessInterviewRequestReviewOpen: ctx.isBusinessInterviewRequestReviewOpen.value,
  closeBusinessInterviewRequestReview: ctx.closeBusinessInterviewRequestReview,
  businessInterviewReviewState: ctx.businessInterviewReviewState,
  selectedBusinessInterviewReviewSchedule: ctx.selectedBusinessInterviewReviewSchedule.value,
  formatBusinessInterviewApplicantResponseLabel: ctx.formatBusinessInterviewApplicantResponseLabel,
  formatBusinessInterviewTypeLabel: ctx.formatBusinessInterviewTypeLabel,
  formatBusinessInterviewDateTime: ctx.formatBusinessInterviewDateTime,
  businessInterviewRequestScheduleOptions: ctx.businessInterviewRequestScheduleOptions.value,
  businessInterviewMinScheduleDateTime: ctx.businessInterviewMinScheduleDateTime.value,
  addBusinessInterviewRequestScheduleOption: ctx.addBusinessInterviewRequestScheduleOption,
  isBusinessInterviewRequestDecisionSubmitting: ctx.isBusinessInterviewRequestDecisionSubmitting.value,
  approveBusinessInterviewRescheduleRequest: ctx.approveBusinessInterviewRescheduleRequest,
  rejectBusinessInterviewRescheduleRequest: ctx.rejectBusinessInterviewRescheduleRequest,
  isHelpCenterModalOpen: ctx.isHelpCenterModalOpen.value,
  closeHelpCenterModal: ctx.closeHelpCenterModal,
  isCreateUserConfirmOpen: ctx.isCreateUserConfirmOpen.value,
  closeCreateUserConfirm: ctx.closeCreateUserConfirm,
  createUserConfirmationName: ctx.createUserConfirmationName.value,
  createUserConfirmationEmail: ctx.createUserConfirmationEmail.value,
  isCreatingWorkspaceUser: ctx.isCreatingWorkspaceUser.value,
  executeWorkspaceUserAccountCreation: ctx.executeWorkspaceUserAccountCreation,
  isLogoutConfirmOpen: ctx.isLogoutConfirmOpen.value,
  closeLogoutConfirm: ctx.closeLogoutConfirm,
  isLogoutSubmitting: ctx.isLogoutSubmitting.value,
  confirmLogout: ctx.confirmLogout,
  isTrialConfirmationOpen: ctx.isTrialConfirmationOpen.value,
  currentCheckoutFlow: ctx.currentCheckoutFlow.value,
  closeTrialConfirmation: ctx.closeTrialConfirmation,
  proceedToPayment: ctx.proceedToPayment,
  isCancelPaymentModalOpen: ctx.isCancelPaymentModalOpen.value,
  closeCancelPaymentModal: ctx.closeCancelPaymentModal,
  isCancellingPayment: ctx.isCancellingPayment.value,
  confirmCancelPayment: ctx.confirmCancelPayment,
  isAddMemberDrawerOpen: ctx.isAddMemberDrawerOpen.value,
  closeAddMemberDrawer: ctx.closeAddMemberDrawer,
  canEditBusinessModule: ctx.canEditBusinessModule,
  isWorkspaceUserDirectoryLoading: ctx.isWorkspaceUserDirectoryLoading.value,
  availableEmployeeLinkOptions: ctx.availableEmployeeLinkOptions.value,
  employeeDraft: ctx.employeeDraft.value,
  selectedEmployeeLinkedUser: ctx.selectedEmployeeLinkedUser.value,
  getWorkspaceUserRoleName: ctx.getWorkspaceUserRoleName,
  employeeEmploymentTypeOptions: ctx.employeeEmploymentTypeOptions,
  employeeStatusOptions: ctx.employeeStatusOptions,
  selectedEmployeeRole: ctx.selectedEmployeeRole.value,
  selectedEmployeeRoleSummary: ctx.selectedEmployeeRoleSummary.value,
  selectedEmployeeRoleModules: ctx.selectedEmployeeRoleModules.value,
  selectedEmployeeRoleModuleSections: ctx.selectedEmployeeRoleModuleSections.value,
  countPermissionRoleEnabledModules: ctx.countPermissionRoleEnabledModules,
  countPermissionRoleFullAccessModules: ctx.countPermissionRoleFullAccessModules,
  resetEmployeeDraft: () => { ctx.employeeDraft.value = ctx.createDefaultEmployeeDraft() },
  saveStaticEmployee: ctx.saveStaticEmployee,
}))
