import { computed } from 'vue'

export const createTeamMemberBindings = (ctx) => computed(() => ({
  activeSection: ctx.activeSection.value,
  currentUserManagementPage: ctx.currentUserManagementPage.value,
  isWorkspaceUserDirectoryLoading: ctx.isWorkspaceUserDirectoryLoading.value,
  workspaceUserDirectory: ctx.workspaceUserDirectory.value,
  permissionRoles: ctx.permissionRoles.value,
  employeeDirectory: ctx.employeeDirectory.value,
  workspaceUserDirectorySyncMessage: ctx.workspaceUserDirectorySyncMessage.value,
  userOverviewCards: ctx.userOverviewCards.value,
  filteredUserOverviewRows: ctx.filteredUserOverviewRows.value,
  userOverviewRoleOptions: ctx.userOverviewRoleOptions.value,
  userOverviewSearch: ctx.userOverviewSearch.value,
  userOverviewRoleFilter: ctx.userOverviewRoleFilter.value,
  userOverviewStatusFilter: ctx.userOverviewStatusFilter.value,
  userOverviewSummary: ctx.userOverviewSummary.value,
  formatUserOverviewDate: ctx.formatUserOverviewDate,
  setUserOverviewSearch: (value) => { ctx.userOverviewSearch.value = value },
  setUserOverviewRoleFilter: (value) => { ctx.userOverviewRoleFilter.value = value },
  setUserOverviewStatusFilter: (value) => { ctx.userOverviewStatusFilter.value = value },
  openCreateUserSection: ctx.openCreateUserSection,
  openPermissionsSection: ctx.openPermissionsSection,
  userAccountDraft: ctx.userAccountDraft.value,
  permissionRoleOptionsForUsers: ctx.permissionRoleOptionsForUsers.value,
  selectedUserAccountRole: ctx.selectedUserAccountRole.value,
  selectedUserAccountRoleSummary: ctx.selectedUserAccountRoleSummary.value,
  selectedUserAccountRoleModules: ctx.selectedUserAccountRoleModules.value,
  selectedUserAccountRoleModuleSections: ctx.selectedUserAccountRoleModuleSections.value,
  canEditBusinessModule: ctx.canEditBusinessModule,
  isCreatingWorkspaceUser: ctx.isCreatingWorkspaceUser.value,
  resetUserAccountDraft: ctx.resetUserAccountDraft,
  saveWorkspaceUserAccount: ctx.saveWorkspaceUserAccount,
  getEmployeeRoleName: ctx.getEmployeeRoleName,
  getEmployeeRoleAccessSummary: ctx.getEmployeeRoleAccessSummary,
  resolveEmployeeStatusClass: ctx.resolveEmployeeStatusClass,
  permissionBindings: ctx.permissionBindings.value,
}))

export const createPermissionBindings = (ctx) => computed(() => ({
  permissionRoles: ctx.permissionRoles.value,
  selectedPermissionRole: ctx.selectedPermissionRole.value,
  selectedPermissionRoleId: ctx.selectedPermissionRoleId.value,
  selectedPermissionEnabledModuleCount: ctx.selectedPermissionEnabledModuleCount.value,
  selectedPermissionFullAccessCount: ctx.selectedPermissionFullAccessCount.value,
  selectedPermissionAssignedUsersCount: ctx.selectedPermissionAssignedUsersCount.value,
  permissionRolesHasUnsavedChanges: ctx.permissionRolesHasUnsavedChanges.value,
  isSavingPermissionRoles: ctx.isSavingPermissionRoles.value,
  isPermissionRoleEditMode: ctx.isPermissionRoleEditMode.value,
  permissionRoleLookupValue: ctx.permissionRoleLookupValue.value,
  permissionRoleDraftName: ctx.permissionRoleDraftName.value,
  permissionModuleSections: ctx.permissionModuleSections,
  canEditBusinessModule: ctx.canEditBusinessModule,
  formatPermissionRoleAccessSummary: ctx.formatPermissionRoleAccessSummary,
  getPermissionModulesForSection: ctx.getPermissionModulesForSection,
  isPermissionModuleFullAccess: ctx.isPermissionModuleFullAccess,
  formatPermissionAccessLabel: ctx.formatPermissionAccessLabel,
  countPermissionRoleEnabledModules: ctx.countPermissionRoleEnabledModules,
  countPermissionRoleFullAccessModules: ctx.countPermissionRoleFullAccessModules,
  countUsersAssignedToRole: ctx.countUsersAssignedToRole,
  togglePermissionRoleEditMode: ctx.togglePermissionRoleEditMode,
  handlePermissionRoleLookupInput: ctx.handlePermissionRoleLookupInput,
  applyPermissionRoleLookupSelection: ctx.applyPermissionRoleLookupSelection,
  removeSelectedPermissionRole: ctx.removeSelectedPermissionRole,
  createPermissionRole: ctx.createPermissionRole,
  savePermissionRoles: ctx.savePermissionRoles,
  updatePermissionModuleAction: ctx.updatePermissionModuleAction,
  updatePermissionModuleFullAccess: ctx.updatePermissionModuleFullAccess,
  setPermissionRoleDraftName: (value) => { ctx.permissionRoleDraftName.value = value },
  setSelectedPermissionRoleId: (value) => { ctx.selectedPermissionRoleId.value = value },
}))
