import { computed } from 'vue'

export const createAssessmentBindings = (ctx) => computed(() => ({
  activeSection: ctx.activeSection.value,
  assessmentUi: ctx.assessmentUi,
  canEditBusinessModule: ctx.canEditBusinessModule,
  editingAssessmentTemplateId: ctx.editingAssessmentTemplateId.value,
  handleAssessmentTemplateSelection: ctx.handleAssessmentTemplateSelection,
  assessmentTemplateLibrary: ctx.assessmentTemplateLibrary.value,
  startNewAssessmentTemplate: ctx.startNewAssessmentTemplate,
  deleteAssessmentTemplate: ctx.deleteAssessmentTemplate,
  saveAssessmentTemplate: ctx.saveAssessmentTemplate,
  assessmentTemplateDraft: ctx.assessmentTemplateDraft.value,
  trainingQuestionTypeOptions: ctx.trainingQuestionTypeOptions,
  addAssessmentTemplateQuestion: ctx.addAssessmentTemplateQuestion,
  resolveTrainingQuestionTypeMeta: ctx.resolveTrainingQuestionTypeMeta,
  removeAssessmentTemplateQuestion: ctx.removeAssessmentTemplateQuestion,
  addAssessmentTemplateOption: ctx.addAssessmentTemplateOption,
  setAssessmentTemplateCorrectOption: ctx.setAssessmentTemplateCorrectOption,
  removeAssessmentTemplateOption: ctx.removeAssessmentTemplateOption,
  normalizeAssessmentPassingScorePercent: ctx.normalizeAssessmentPassingScorePercent,
  approvedApplicantTemplateAssignments: ctx.approvedApplicantTemplateAssignments.value,
  assignedApplicantTemplateRows: ctx.assignedApplicantTemplateRows.value,
  assignableAssessmentTemplates: ctx.assignableAssessmentTemplates.value,
  handleAssessmentAssignmentTemplateSelection: ctx.handleAssessmentAssignmentTemplateSelection,
  canRemoveAssignedAssessment: ctx.canRemoveAssignedAssessment,
  requestAssignAssessmentTemplateToApplicant: ctx.requestAssignAssessmentTemplateToApplicant,
  removeAssignedAssessmentFromApplicant: ctx.removeAssignedAssessmentFromApplicant,
  getAssignableTemplateLabel: ctx.getAssignableTemplateLabel,
  applicantScoreRows: ctx.applicantScoreRows.value,
  applicantScoreFilters: ctx.applicantScoreFilters,
  applicantScoreRoleOptions: ctx.applicantScoreRoleOptions.value,
  openAssessmentAssignmentsSection: ctx.openAssessmentAssignmentsSection,
  applicantScoreSummary: ctx.applicantScoreSummary.value,
  filteredApplicantScoreRows: ctx.filteredApplicantScoreRows.value,
}))
