import { computed } from 'vue'

export const createInterviewBindings = (ctx) => computed(() => ({
  interviewSchedulingTab: ctx.interviewSchedulingTab.value,
  setInterviewSchedulingTab: ctx.setInterviewSchedulingTab,
  businessInterviewScheduleStats: ctx.businessInterviewScheduleStats.value,
  isBusinessInterviewRefreshing: ctx.isBusinessInterviewRefreshing.value,
  refreshBusinessInterviewApplicants: ctx.refreshBusinessInterviewApplicants,
  businessInterviewSchedulingFormError: ctx.businessInterviewSchedulingFormError.value,
  canEditBusinessModule: ctx.canEditBusinessModule,
  businessInterviewSchedulingForm: ctx.businessInterviewSchedulingForm.value,
  createBusinessInterviewSchedule: ctx.createBusinessInterviewSchedule,
  businessInterviewAcceptedJobOptions: ctx.businessInterviewAcceptedJobOptions.value,
  businessInterviewFilteredApplicants: ctx.businessInterviewFilteredApplicants.value,
  businessInterviewTechnicalGateHint: ctx.businessInterviewTechnicalGateHint.value,
  businessInterviewAvailableInterviewTypeOptions: ctx.businessInterviewAvailableInterviewTypeOptions.value,
  businessInterviewMinScheduleDateTime: ctx.businessInterviewMinScheduleDateTime.value,
  resetBusinessInterviewSchedulingForm: ctx.resetBusinessInterviewSchedulingForm,
  shiftBusinessInterviewCalendarMonth: ctx.shiftBusinessInterviewCalendarMonth,
  businessInterviewCalendarMonthLabel: ctx.businessInterviewCalendarMonthLabel.value,
  businessInterviewWeekdayLabels: ctx.businessInterviewWeekdayLabels.value,
  businessInterviewCalendarDays: ctx.businessInterviewCalendarDays.value,
  selectBusinessInterviewCalendarDay: ctx.selectBusinessInterviewCalendarDay,
  businessInterviewSelectedCalendarLabel: ctx.businessInterviewSelectedCalendarLabel.value,
  businessInterviewSelectedDaySchedules: ctx.businessInterviewSelectedDaySchedules.value,
  formatBusinessInterviewTime: ctx.formatBusinessInterviewTime,
  businessInterviewStatusSummary: ctx.businessInterviewStatusSummary.value,
  businessInterviewStatusRows: ctx.businessInterviewStatusRows.value,
  resolveBusinessInterviewStatusBadgeClass: ctx.resolveBusinessInterviewStatusBadgeClass,
  openBusinessInterviewRequestReview: ctx.openBusinessInterviewRequestReview,
  completeBusinessInterviewSchedule: ctx.completeBusinessInterviewSchedule,
}))
